version: 2
jobs:
  build:
    environment:
      # You must replace the CC_TEST_REPORTER_ID with the one of your project
      CC_TEST_REPORTER_ID: 89b5ee3c59b8aeeb88ddc2f5469410dc9e0fb800ec4346a54a759bfc4eccb6b3
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
      - image: circleci/mysql:latest

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: cp .circleci/database.yml config/database.yml
      - run: cp .circleci/application.yml config/application.yml
      - run: RAILS_ENV=test bundle exec rake db:create
      - run: RAILS_ENV=test bundle exec rake db:schema:load

      - run:
          name: run tests
          command: RAILS_ENV=test bundle exec rspec

      # run rails_best_practices!
      - run:
          name: run rails best practices
          command: RAILS_ENV=test bundle exec rake rails_best_practices

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      # run codeclimate!
      # - run:
      #     name: Setup Code Climate test-reporter
      #     command: |
      #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #       chmod +x ./cc-test-reporter
      #       ./cc-test-reporter before-build
      #       ./cc-test-reporter after-build
